class TopicData{
  final String _topicImage;
  final String _topicName;
  TopicData(this._topicImage, this._topicName);
  String getTopicImage(){ return _topicImage; }
  String getTopicName(){ return _topicName; }
}
  final allTopics = <TopicData>[
  TopicData("assets/images/topicIcons/icon_greetings.png", "Greetings"),
  TopicData("assets/images/topicIcons/icon_numbers.png", "Numbers"),
  TopicData("assets/images/topicIcons/icon_colour.png", "Colours"),
  TopicData("assets/images/topicIcons/icon_drinks.png", "Drinks"),
  TopicData("assets/images/topicIcons/icon_meals.png", "Food - Meal"),
  TopicData("assets/images/topicIcons/icon_cookeddishes.png", "Food - Dishes"),
  TopicData("assets/images/topicIcons/icon_foodmeat.png", "Food - Meat"),
  TopicData("assets/images/topicIcons/icon_foodsea.png", "Food - Sea"),
  TopicData("assets/images/topicIcons/icon_breadcandy.png", "Food - Baked"),
  TopicData("assets/images/topicIcons/icon_vegetables.png", "Vegetables"),
  TopicData("assets/images/topicIcons/icon_fruitsnuts.png", "Fruit and Nut"),
  TopicData("assets/images/topicIcons/icon_spices.png", "Spices"),
  TopicData("assets/images/topicIcons/icon_clothing.png", "Clothing"),
  TopicData("assets/images/topicIcons/icon_fabrics.png", "Fabrics"),
  TopicData("assets/images/topicIcons/icon_coat.png", "Coats"),
  TopicData("assets/images/topicIcons/icon_headwear.png", "Head Wear"),
  TopicData("assets/images/topicIcons/icon_footwear.png", "Foot Wear"),
  TopicData("assets/images/topicIcons/icon_undergarment.png", "Undergarment"),
  TopicData("assets/images/topicIcons/icon_watches.png", "Watches"),
  TopicData("assets/images/topicIcons/icon_jewelry.png", "Jewelry"),
  TopicData("assets/images/topicIcons/icon_accessories.png", "Accessories"),
  TopicData("assets/images/topicIcons/icon_cosmetics.png", "Cosmetics"),
  TopicData("assets/images/topicIcons/icon_hours.png", "Time and Days"),
  TopicData("assets/images/topicIcons/icon_animals.png", "Animals"),
  TopicData("assets/images/topicIcons/icon_birds.png", "Birds"),
  TopicData("assets/images/topicIcons/icon_fish.png", "Fish"),
  TopicData("assets/images/topicIcons/icon_insects.png", "Insects"),
  TopicData("assets/images/topicIcons/icon_emotions.png", "Emotions"),
  TopicData("assets/images/topicIcons/icon_luck.png", "Luck"),
  TopicData("assets/images/topicIcons/icon_languages.png", "Languages"),
  TopicData("assets/images/topicIcons/icon_conversation.png", "Conversation"),
  TopicData("assets/images/topicIcons/icon_agreerefuse.png", "Agree - Refuse"),
  TopicData("assets/images/topicIcons/icon_humans.png", "Humans"),
  TopicData("assets/images/topicIcons/icon_anatomy.png", "Anatomy"),
  TopicData("assets/images/topicIcons/icon_head.png", "Head"),
  TopicData("assets/images/topicIcons/icon_body.png", "Body"),
  TopicData("assets/images/topicIcons/icon_diseases.png", "Diseases"),
  TopicData("assets/images/topicIcons/icon_symptoms.png", "Symptoms"),
  TopicData("assets/images/topicIcons/icon_doctors.png", "Doctor"),
  TopicData("assets/images/topicIcons/icon_drugs.png", "Medicine"),
  TopicData("assets/images/topicIcons/icon_smoking.png", "Smoking"),
  TopicData("assets/images/topicIcons/icon_city.png", "City"),
  TopicData("assets/images/topicIcons/icon_institutions.png", "Institutions"),
  TopicData("assets/images/topicIcons/icon_signs.png", "Signs"),
  TopicData("assets/images/topicIcons/icon_transportation.png", "Transportation"),
  TopicData("assets/images/topicIcons/icon_cars.png", "Cars"),
  TopicData("assets/images/topicIcons/icon_train.png", "Train"),
  TopicData("assets/images/topicIcons/icon_sightseeing.png", "Sightseeing"),
  TopicData("assets/images/topicIcons/icon_shopping.png", "Shopping"),
  TopicData("assets/images/topicIcons/icon_money.png", "Money"),
  TopicData("assets/images/topicIcons/icon_postservice.png", "Post Service"),
  TopicData("assets/images/topicIcons/icon_school.png", "School"),
  TopicData("assets/images/topicIcons/icon_university.png", "University"),
  TopicData("assets/images/topicIcons/icon_house.png", "House"),
  TopicData("assets/images/topicIcons/icon_bathroom.png", "Bathroom"),
  TopicData("assets/images/topicIcons/icon_kitchen.png", "Kitchen"),
  TopicData("assets/images/topicIcons/icon_appliances.png", "Appliances"),
  TopicData("assets/images/topicIcons/icon_computer.png", "Computer"),
  TopicData("assets/images/topicIcons/icon_internet.png", "Internet"),
  TopicData("assets/images/topicIcons/icon_repairs.png", "Repairs"),
  TopicData("assets/images/topicIcons/icon_plumbing.png", "Plumbing"),
  TopicData("assets/images/topicIcons/icon_conflagration.png", "Conflagration"),
  TopicData("assets/images/topicIcons/icon_office.png", "Office"),
  TopicData("assets/images/topicIcons/icon_business.png", "Business"),
  TopicData("assets/images/topicIcons/icon_production.png", "Production"),
  TopicData("assets/images/topicIcons/icon_contract.png", "Contract"),
  TopicData("assets/images/topicIcons/icon_importexport.png", "Import Export"),
  TopicData("assets/images/topicIcons/icon_finances.png", "Finances"),
  TopicData("assets/images/topicIcons/icon_marketing.png", "Marketing"),
  TopicData("assets/images/topicIcons/icon_advertising.png", "Advertising"),
  TopicData("assets/images/topicIcons/icon_banking.png", "Banking"),
  TopicData("assets/images/topicIcons/icon_telephone.png", "Telephone"),
  TopicData("assets/images/topicIcons/icon_stationery.png", "Stationery"),
  TopicData("assets/images/topicIcons/icon_documents.png", "Documents"),
  TopicData("assets/images/topicIcons/icon_shapes.png", "Shapes"),
  TopicData("assets/images/topicIcons/icon_uom.png", "Measurement"),
  TopicData("assets/images/topicIcons/icon_materials.png", "Materials"),
  TopicData("assets/images/topicIcons/icon_metals.png", "Metals"),
  TopicData("assets/images/topicIcons/icon_agriculture.png", "Agriculture"),
  TopicData("assets/images/topicIcons/icon_forest.png", "Forest"),
  TopicData("assets/images/topicIcons/icon_weather.png", "Weather"),
  TopicData("assets/images/topicIcons/icon_building.png", "Buildings"),
  TopicData("assets/images/topicIcons/icon_hotel.png", "Hotel"),
  TopicData("assets/images/topicIcons/icon_restaurant.png", "Restaurant"),
  TopicData("assets/images/topicIcons/icon_research.png", "Scientific"),
  TopicData("assets/images/topicIcons/icon_jobsearch.png", "Job Search"),
  TopicData("assets/images/topicIcons/icon_laworder.png", "Law and Order"),
  TopicData("assets/images/topicIcons/icon_military.png", "Military"),
  TopicData("assets/images/topicIcons/icon_war.png", "War"),
  TopicData("assets/images/topicIcons/icon_gym.png", "Gym"),
  TopicData("assets/images/topicIcons/icon_sports.png", "Sports"),
  TopicData("assets/images/topicIcons/icon_countries.png", "Countries"),
  TopicData("assets/images/topicIcons/icon_questions.png", "Questions"),
  TopicData("assets/images/topicIcons/icon_prepositions.png", "Prepositions"),
  TopicData("assets/images/topicIcons/icon_verbs.png", "Verbs - P1"),
  TopicData("assets/images/topicIcons/icon_verbs.png", "Verbs - P2"),
  TopicData("assets/images/topicIcons/icon_verbs.png", "Verbs - P3"),
  TopicData("assets/images/topicIcons/icon_verbs.png", "Verbs - P4"),
  TopicData("assets/images/topicIcons/icon_adjs.png", "Adjectives - P1"),
  TopicData("assets/images/topicIcons/icon_adjs.png", "Adjectives - P2"),
  TopicData("assets/images/topicIcons/icon_adverbs.png", "Adverbs - P1"),
  TopicData("assets/images/topicIcons/icon_adverbs.png", "Adverbs - P2")
];

var allTopicsFilter = allTopics;